services:
  fastify:
    build: .
    command: npm run dev
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    volumes:
      - ./src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DB_URL=${DB_URL}

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: op
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: